---
collections:
  - name: community.docker
    version: 5.0.1
  - name: community.general
    version: 12.0.0
  - name: ansible.posix
    version: 2.1.0
  - name: artis3n.tailscale
    version: 1.1.0
  - name: awx.awx
    version: 24.6.1
  - name: community.beszel
    version: 0.5.0
roles:
  - name: dbrennand.caddy_docker
    version: 4.0.0
  - name: dbrennand.autorestic
    version: 1.4.0
  - name: geerlingguy.docker
    version: 7.8.0
  - name: geerlingguy.pip
    version: 3.1.1
  - name: geerlingguy.security
    src: https://github.com/dbrennand/ansible-role-security
    version: refactor/ssh-regexp
  - name: ironicbadger.figurine
    src: https://github.com/ironicbadger/ansible-role-figurine
    version: main
  - name: geerlingguy.repo-epel
    version: 3.1.1
  - name: xanmanning.k3s
    version: v3.6.1
