---
# Config for https://github.com/dbrennand/NextDNS-Rewrites
profile_name: "Main"

rewrites:
  # A Records
  # 192.168.0.2 is free
  # 192.168.0.3 is free
  - name: proxmox01.net.dbren.uk
    content: 192.168.0.4
  # 192.168.0.5 is free
  - name: backup01.net.dbren.uk
    content: 192.168.0.6
  - name: exit01.net.dbren.uk
    content: 192.168.0.7
  # 192.168.0.8 is free
  - name: media01.net.dbren.uk
    content: 192.168.0.9
  - name: stirling.net.dbren.uk
    content: 192.168.0.9
  - name: talos01.net.dbren.uk
    content: 192.168.0.10
  - name: awx.net.dbren.uk
    content: 192.168.0.10
  # 192.168.0.11 is free
  # 192.168.0.12 is free
