---
services:
  tailscale:
    image: ghcr.io/tailscale/tailscale:v1.90.6
    container_name: tailscale_beszel
    hostname: beszel
    restart: unless-stopped
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}?ephemeral=false
      - TS_EXTRA_ARGS=--accept-routes --advertise-tags=tag:beszel-hub
      - TS_ACCEPT_DNS=true
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_SERVE_CONFIG=/config/serve.json
    volumes:
      - tailscale_beszel:/var/lib/tailscale
      - ./config:/config
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
  beszel:
    image: ghcr.io/henrygd/beszel/beszel:0.15.4
    container_name: beszel
    restart: unless-stopped
    depends_on:
      - tailscale
    network_mode: service:tailscale
    volumes:
      - ./beszel_data:/beszel_data

volumes:
  tailscale_beszel:
